version: "3.8"

services:
  vimapix:
    image: vimasistemas/vimapix:latest
    hostname: vimapix
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      labels:
        # --- Configurações do Traefik ---
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        # Roteador HTTP para o domínio
        - "traefik.http.routers.vimapix.rule=Host(`vimapix.dominio.com.br`)"
        - "traefik.http.routers.vimapix.entrypoints=websecure"
        - "traefik.http.routers.vimapix.service=vimapix-svc"
        # Configurações de TLS/SSL com Let's Encrypt
        - "traefik.http.routers.vimapix.tls=true"
        - "traefik.http.routers.vimapix.tls.certresolver=letsencryptresolver"
        # Definição do serviço e porta da aplicação
        - "traefik.http.services.vimapix-svc.loadbalancer.server.port=3000"

networks:
  network_public:
    external: true
